#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

sudo apt-get update && sudo apt-get install -y inotify-tools

# Update node
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

# Install faketime
git clone https://github.com/wolfcw/libfaketime.git
(cd libfaketime/src && sudo make install)
rm -rf libfaketime